[project]
name = "recollex"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "osx-arm64", "win-64"]

[tool.pixi]
resolver = "uv"

[environments]
default  = { features = ["cpu"], solve-group = "cpu"}
dev      = { features = ["cpu","dev"], solve-group = "cpu" }  
nlp      = { features = ["cpu","dev","nlp"], solve-group = "nlp" } 
cuda     = { features = ["cuda"], solve-group = "cuda" } 
directml = { features = ["directml"], solve-group = "directml" } 
silicon  = { features = ["silicon"], solve-group = "silicon" }

[dependencies]
python = ">=3.10,<3.14"
numpy = "*"
scipy = "*"

[pypi-dependencies]
recollex-gpu = { path = ".", editable = true }

[feature.dev.pypi-dependencies]
ipython = ">=8,<9"
pytest = "*"
pytest-cov = "*"

[feature.nlp]
platforms = ["linux-64","win-64","osx-arm64"]     # exclude osx-64
dependencies = { python = ">=3.10,<3.13" }        # torch wheels exist here
pypi-dependencies = { sentence-transformers = { version = ">=5.1,<6", extras = ["onnx"] } }

[feature.cpu.pypi-dependencies]
onnxruntime = ">=1.17"

[feature.cuda]
platforms = ["linux-64", "win-64"] 
pypi-dependencies = { onnxruntime-gpu = ">=1.17" }

# [feature.rocm]
# platforms = ["linux-64"]
# dependencies = { python = "==3.10" }
# pypi-dependencies = { onnxruntime-rocm = ">=1.17" }

[feature.directml]
platforms = ["win-64"]
pypi-dependencies = { onnxruntime-directml = ">=1.17" }

[feature.silicon]
platforms = ["osx-arm64"]
dependencies = { python = ">=3.10,<3.12" }

[feature.silicon.pypi-dependencies] 
recollex-gpu = { path = ".", editable = true, extras = ["silicon"] }
 
[tasks]
test = "pytest -q"
clean = "recollex-clean"
prefetch = "recollex-prefetch"
