[project]
name = "recollex"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64", "osx-64", "win-64"]

[environments]
default = { features = ["dev"], solve-group = "default" }

[tool.pixi]
resolver = "uv"                # still resolves PyPI deps with uv

# Pin Python
[tool.pixi.system-requirements]
python = "3.12"

# Your package itself is still editable
pypi-dependencies = { your-package-name = { path = ".", editable = true } }

[dependencies]                 # conda-forge deps
python = "3.12.*"
numpy = "*"
scipy = "*"

[feature.dev.pypi-dependencies]
ipython = ">=8,<9"
pytest = "*"
pytest-cov = "*"

[tasks]
test = "pytest -q"