[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "recollex-directml"
version = "0.1.0"
description = "DirectML meta-package for Recollex (depends on recollex-core + onnxruntime-directml)"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "recollex-core>=0.1.0",
    "onnxruntime-directml>=1.17",
]

[tool.setuptools]
packages = []
